name: CD
on:
  push:
    branches:
      - main
      - backport/*.*
    paths:
      - config/**
      - spack.yaml
jobs:
  cd:
    name: CD
    # NOTE: We are using this specific tag of the deployment infra as the current HEAD of v8 works with a new spack-config that isn't yet migrated to the release instance.  
    uses: access-nri/build-cd/.github/workflows/cd.yml@v8.3.3
    with:
      model: ${{ vars.NAME }}
      spack-manifest-schema-version: 2-0-0
      config-versions-schema-version: 4-0-0
      config-packages-schema-version: 1-0-0
    permissions:
      contents: write
      # Required because later workflows also handle on.pull_request trigger
      pull-requests: write
    secrets: inherit
